ALTER TABLE products
  ALTER COLUMN price_vnd DROP DEFAULT,
  ALTER COLUMN price_vnd TYPE TEXT USING TRIM(TRAILING '.' FROM TRIM(TRAILING '0' FROM price_vnd::text)),
  ALTER COLUMN price_vnd SET DEFAULT '0',
  ALTER COLUMN price_vnd SET NOT NULL;
